#ifndef REGISTER_KEY_NAME 
#define REGISTER_KEY_NAME(name) BEARENGINE_API extern  BearName Key##name;
#endif
REGISTER_KEY_NAME(A);
REGISTER_KEY_NAME(B);
REGISTER_KEY_NAME(C);
REGISTER_KEY_NAME(D);
REGISTER_KEY_NAME(E);
REGISTER_KEY_NAME(F);
REGISTER_KEY_NAME(G);
REGISTER_KEY_NAME(H);
REGISTER_KEY_NAME(I);
REGISTER_KEY_NAME(J);
REGISTER_KEY_NAME(K);
REGISTER_KEY_NAME(L);
REGISTER_KEY_NAME(M);
REGISTER_KEY_NAME(N);
REGISTER_KEY_NAME(O);
REGISTER_KEY_NAME(P);
REGISTER_KEY_NAME(Q);
REGISTER_KEY_NAME(R);
REGISTER_KEY_NAME(S);
REGISTER_KEY_NAME(T);
REGISTER_KEY_NAME(U);
REGISTER_KEY_NAME(V);
REGISTER_KEY_NAME(W);
REGISTER_KEY_NAME(X);
REGISTER_KEY_NAME(Y);
REGISTER_KEY_NAME(Z);

REGISTER_KEY_NAME(Num0);
REGISTER_KEY_NAME(Num1);
REGISTER_KEY_NAME(Num2);
REGISTER_KEY_NAME(Num3);
REGISTER_KEY_NAME(Num4);
REGISTER_KEY_NAME(Num5);
REGISTER_KEY_NAME(Num6);
REGISTER_KEY_NAME(Num7);
REGISTER_KEY_NAME(Num8);
REGISTER_KEY_NAME(Num9);

REGISTER_KEY_NAME(Escape);
REGISTER_KEY_NAME(LControl);
REGISTER_KEY_NAME(LShift);
REGISTER_KEY_NAME(LAlt);
REGISTER_KEY_NAME(LSystem);
REGISTER_KEY_NAME(RControl);
REGISTER_KEY_NAME(RShift);
REGISTER_KEY_NAME(RAlt);
REGISTER_KEY_NAME(RSystem);
REGISTER_KEY_NAME(Menu);
REGISTER_KEY_NAME(LBracket);
REGISTER_KEY_NAME(RBracket);
REGISTER_KEY_NAME(SemiColon);
REGISTER_KEY_NAME(Comma);
REGISTER_KEY_NAME(Period);
REGISTER_KEY_NAME(Quote);
REGISTER_KEY_NAME(Slash);
REGISTER_KEY_NAME(BackSlash);
REGISTER_KEY_NAME(Tilde);
REGISTER_KEY_NAME(Equal);
REGISTER_KEY_NAME(Dash);
REGISTER_KEY_NAME(Space);
REGISTER_KEY_NAME(Return);
REGISTER_KEY_NAME(BackSpace);
REGISTER_KEY_NAME(Tab);
REGISTER_KEY_NAME(PageUp);
REGISTER_KEY_NAME(PageDown);
REGISTER_KEY_NAME(End);
REGISTER_KEY_NAME(Home);
REGISTER_KEY_NAME(Insert);
REGISTER_KEY_NAME(Delete);
REGISTER_KEY_NAME(Add);
REGISTER_KEY_NAME(Subtract);
REGISTER_KEY_NAME(Multiply);
REGISTER_KEY_NAME(Divide);

REGISTER_KEY_NAME(Left);
REGISTER_KEY_NAME(Right);
REGISTER_KEY_NAME(Up);
REGISTER_KEY_NAME(Down);

REGISTER_KEY_NAME(Numpad0);
REGISTER_KEY_NAME(Numpad1);
REGISTER_KEY_NAME(Numpad2);
REGISTER_KEY_NAME(Numpad3);
REGISTER_KEY_NAME(Numpad4);
REGISTER_KEY_NAME(Numpad5);
REGISTER_KEY_NAME(Numpad6);
REGISTER_KEY_NAME(Numpad7);
REGISTER_KEY_NAME(Numpad8);
REGISTER_KEY_NAME(Numpad9);

REGISTER_KEY_NAME(F1);
REGISTER_KEY_NAME(F2);
REGISTER_KEY_NAME(F3);
REGISTER_KEY_NAME(F4);
REGISTER_KEY_NAME(F5);
REGISTER_KEY_NAME(F6);
REGISTER_KEY_NAME(F7);
REGISTER_KEY_NAME(F8);
REGISTER_KEY_NAME(F9);
REGISTER_KEY_NAME(F10);
REGISTER_KEY_NAME(F11);
REGISTER_KEY_NAME(F12);
REGISTER_KEY_NAME(F13);
REGISTER_KEY_NAME(F14);
REGISTER_KEY_NAME(F15);

REGISTER_KEY_NAME(Pause);

REGISTER_KEY_NAME(MouseLeft);
REGISTER_KEY_NAME(MouseRight);
REGISTER_KEY_NAME(MouseMiddle);

REGISTER_KEY_NAME(MouseScrollUp);
REGISTER_KEY_NAME(MouseScrollDown);
#undef REGISTER_KEY_NAME